undefinedorgcr/gostarkme-backend

- CONTRIBUTORS_GUIDE.md
feat: add Contributors_guide readme
> feat: add Contributors_guide readme

- contracts/src/fund.cairo
> [19] Add asserts to funds contract

- contracts/README.md
- contracts/Scarb.lock
- contracts/Scarb.toml
- contracts/src/donator.cairo
- contracts/src/lib.cairo
- contracts/tests/test_donator.cairo
1.  Add new backend readme
2. Add snforge_std and openzeppelin dependencies in scarb.toml
3. Make IDonator trait public
4. fix updateDonatorValues method because the total_stark_donations was not updated
5. make all the modules public in lib.cairo
6. Add donator tests
closes #42
> [feat] Add donators contract tests

- .gitignore
- frontend/gostarkme-web/app/globals.css
- frontend/gostarkme-web/app/guidelines/charity/page.tsx
- frontend/gostarkme-web/app/guidelines/projects/page.tsx
- frontend/gostarkme-web/app/page.tsx
- frontend/gostarkme-web/components/ui/LinkButton.tsx
> [feat] added guidelines pages

- .github/workflows/nextjs.yml
> [CI] added env var when building with next js

- .github/workflows/contract_checks.yml
- contracts/Scarb.toml
- scripts/run_tests.sh
Closes #64 
- Add bash script to navigate to contracts folder and run testing command
- Add [script] tag to `Scarb.toml` to run `snforge test` with `scarb run test`
- Add `run-tests` workflow to existing CI pipeline.
Let me know if you have any feedback!
> [feat] Add testing to CI pipeline

- contracts/src/fundManager.cairo
Will be implemented in ODHack
This PR will add the class hash of the funds contracts to storage so we can call them in the constructor making sure we can deploy the contract using the desired class hash.
Not necessary
> [update] added fund class hash to constructor and storage

- contracts/src/fund.cairo
- contracts/src/fundManager.cairo
- contracts/tests/test_fund.cairo
This will change the fund contract to use ByteArray for reason and not sending the reason when deploying a fund.
> [fix] Using ByteArray to represent reason

- frontend/gostarkme-web/components/ui/Navbar.tsx
- Closes #85
This PR enhances the Navbar component by introducing props for dynamic content, improving its reusability and flexibility across the application.
- Modified the Navbar component in `components/Navbar.tsx` to accept props for customizable content.
- Implemented TypeScript interfaces for proper type checking of component props.
- Refactored the component to use passed props instead of hardcoded values.
- `logoSrc`: For customizable logo source
- `logoAlt`: For accessible alt text for the logo
- `title`: For customizable navbar title
- `navItems`: An array of navigation items (label and href)
- `ctaButton`: For customizable call-to-action button (label and href)
- Maintained the existing responsive design, ensuring the component works well on both mobile and desktop views. …
> feat: create navbar component

- frontend/gostarkme-web/animations/StardustAnimation.tsx
- frontend/gostarkme-web/app/app/myfunds/[useraddr]/page.tsx
- frontend/gostarkme-web/components/modules/myfunds/FundCard.tsx
- frontend/gostarkme-web/components/modules/myfunds/UserFunds.tsx
- frontend/gostarkme-web/components/ui/Button.tsx
1.  Add `myfunds` page
2. Create `FundCard` component
3. Create `UserFunds` component
4. Allow `Button` UI component to receive `className` for custom classes 
// TODO: Implement new fund action
// TODO: Implement funds fetching using 'userAddress'
// TODO: Implement fund deletion based on a unique id or receive the fund object and delete it
1.5 - 2 hours
- URL to access and check the page: http://localhost:3000/app/myfunds/0x01a9222d495ffdba8d0d4c32c53b19348acf525fc8a34bf1c95476bc977e1c23
- Figma design specs: https://www.figma.com/design/SCiGViaoPT9UTrT7CsLbAt/Go-Stark-Me?node-id=0-1&node-type=canvas&t=9SSNtvTO4KS4DcIC-0
> Feat: Add users funds page

- contracts/src/fundManager.cairo
Fix: move increment id because the first fund was with id 0.
> Fix: move increment id because the first fund was with id 0.

- contracts/src/fundManager.cairo
- contracts/tests/test_fund_manager.cairo
* Create new tests for the FundManager contract
* New tests to cover all the methods in the contract
Tests:
* 1 day
* The effort involves research about how to implement the tests and taking inspiration issues pr like -#87 to understand a better way to implement the tests.
No comments
> feat: test_fund_manager

- frontend/gostarkme-web/.gitignore
- frontend/gostarkme-web/app/app/myprofile/[useraddr]/page.tsx
- frontend/gostarkme-web/app/app/page.tsx
- frontend/gostarkme-web/components/modules/myfunds/UserFunds.tsx
- frontend/gostarkme-web/components/ui/Bounded.tsx
- This PR will add the navigation to the entire application.
- Add files to the gitignore.
We are currently navigating with a dummy "1" address, once the Connect Wallet is implemented, we will need to navigate using this address retrieving it from local storage.
> [feat] adding navigation to the entire app

- README.md
- contracts/README.md
- Fix backend readme, remove chatgpt generic documentation. Only setup env info 
- Add Daniel Garbanzo in main readme.
- Remove uml from main readme
Backend readme:
Main readme:
> Fix readme

- contracts/src/constants/donator/donator_constants.cairo
- contracts/src/constants/funds/fund_constants.cairo
- contracts/src/donator.cairo
- contracts/src/fund.cairo
Closes #129 
Modify the data types across smart contracts and constants to `u256` to handle ERC20 token transactions
Necessary refactor to start working on #120 and #121 properly.
> refactor: change data types to handle ERC20 tokens

- contracts/src/fund.cairo
This PR adds `DonationWithdraw` event for `fn withdraw` in `fund.cairo` file, using `owner_address` as the key and `withdrawn_amount` as the data.
The example output is:
```
"events": [
{
"from_address": "0x27d07155a12554d4fd785d0b6d80c03e433313df03bb57939ec8fb0652dbe79", //Contract Address
"keys": [
"0x426f6f6b4164646564",  // selector!("DonationWithdraw")
"0x27d070b6db5703e433313df0939ec8fb0680c155a12554d4fd785d3b52dbe79" // Owner address
],
"data": [
"0x208b7fff7fff7ffe", //withdrawn_amount (u256 STRK)
]
}
]
```
Where: 
- first key =  `selector!("DonationWithdraw")`
- second key = `Owner address`
- data = `withdrawn_amount`
Event Struct: 
```
pub struct DonationWithdraw {
#[key]
pub owner_address: ContractAddress,
pub withdrawn_amount: u256
}
```
2 hours aprox spent
I look forward to …
> [feat] Emit event when user withdraw fund's balance

- contracts/src/fund.cairo
- contracts/tests/test_fund_manager.cairo
* create an event NewVoteReceived in the Fund contract
* Emit such event when call receiveVote function
1 hour
I'm happy to contribute! I stay attentive to any feedback or needed modification
> [test] #137 implement newVoteReceived event on Fund contract

- contracts/.snfoundry_cache/.prev_tests_failed
- contracts/src/constants/funds.cairo
- contracts/src/constants/funds/fund_manager_constants.cairo
- contracts/src/fund.cairo
- contracts/tests/test_fund.cairo
1. Create the `fund_manager_constants.cairo` file in `contracts/src/constants/funds/`:
-   File name: `fund_manager_constants.cairo`.
-   Add a constant called `FUND_MANAGER_ADDRESS` with the fund manager's address.
```cairo
pub mod FundManagerConstants {
pub const FUND_MANAGER_ADDRESS: felt252 =
0x00a885638f5167da8c38f115077c23ed7411539ea8f019ef09ec025d0c52d0ff;
}
```
2. Import the `fund_manager_constants` module in `contracts/src/constants/fund.cairo`:
-   Modify `fund.cairo` to import the new fund manager constants module:
```cairo
pub mod state_constants;
pub mod fund_constants;
pub mod fund_manager_constants;
pub mod starknet_constants;
```
3. Import fund manager constants in the Fund contract (`contracts/src/fund.cairo`):
-   Add the following `use` statement to access the constants …
> fix: Ensure only fund manager can modify goal in setGoal

- contracts/src/fund.cairo
Open
- Add emit event to receiveDonation function
- create a new struct
```cairo
#[derive(Drop, starknet::Event)]
pub struct DonationReceived {
#[key]
pub donor_address: ContractAddress,
pub donated_strks: u256,
pub current_balance: u256,
pub fund_contract_address: ContractAddress,
}
```
- Update Event
```
enum Event {
DonationWithdraw: DonationWithdraw,
NewVoteReceived: NewVoteReceived,
DonationReceived: DonationReceived,
}
```
< 5hrs
formatted using `scarb fmt`
> feat: add emit event to receiveDonation function

- frontend/gostarkme-web/app/app/myfunds/page.tsx
- frontend/gostarkme-web/app/app/myprofile/page.tsx
- frontend/gostarkme-web/app/app/page.tsx
- frontend/gostarkme-web/constants/index.ts
Fixes #163  
- Created a single `navItems` constant in `constants/index.ts`
- Updated each page component to import `navItems` from `constants/index.ts`
- Thoroughly tested the refactored navigation to confirm that it functions consistently across all pages.
Thanks for the opportunity to contribute to this project.
> [fix] Refactor navBarItems

- frontend/gostarkme-web/app/app/page.tsx
- frontend/gostarkme-web/components/dashboard/fundCard.tsx
- frontend/gostarkme-web/components/ui/Bounded.tsx
- frontend/gostarkme-web/constants/index.ts
- frontend/gostarkme-web/contracts/abis/fund.ts
- frontend/gostarkme-web/contracts/abis/fundManager.ts
This PR will use starknetjs to fetch the funds name and description directly from a contract in sepolia network
> [feat] fetch funds using contract functions

- contracts/src/fund.cairo
- contracts/tests/test_fund.cairo
-  Closes #145 
-  Added tests: test_new_vote_received_event_emitted_successful
This adds a test to verify that the NewVoteReceived event is correctly emitted when a user votes. It checks that the event includes the right voter address, fund address, and vote count.
> Fund test event emit

- contracts/src/fund.cairo
- [] Added tests (if necessary)
Fix asserts in withdraw method
Add approve before withdraw
> Fix withdraw asserts and add approve method.

- contracts/src/constants/funds/fund_constants.cairo
- contracts/src/fundManager.cairo
- contracts/tests/test_fund_manager.cairo
In the constants file create the new constant with the minimum required, import that constant to the fundManager file with its storage and constructor and use it
4 hours
> set minimun goal const

- frontend/gostarkme-web/app/app/page.tsx
- Deleted the `<h1>` tag containing `"Latest Funds"`.
- Added some margin to the `funds` section and `Loading funds` div
Took a few minutes to write the code.
@all-contributors please add @wheval for code
The `npm run lint` failed to run.
> fix: delete Latest funds header and add margin to funds section

- frontend/gostarkme-web/components/ui/LoadingSpinner.tsx
This Pull Request adds a loading spinner component to enhance user experience during loading states. The spinner uses `framer-motion` to create a smooth rotating animation.
- Brainstorming the loading spinner design: 15 minutes
- Component development and animation setup: 30 minutes
- Discussion with @adrianvrj for feedback and adjustments: 40 minutes
The component is inside the components/ui folder, thanks for letting me contribute. :)
> feat: add loading spinner component

- contracts/README.md
> fix readme backend

- contracts/src/donator.cairo
- contracts/src/donatorManager.cairo
- contracts/src/fund.cairo
- contracts/src/fundManager.cairo
- contracts/tests/test_donator.cairo
- contracts/tests/test_donator_manager.cairo
- contracts/tests/test_fund.cairo
- contracts/tests/test_fund_manager.cairo
>  "[fix] Update contracts variable and function names"

- contracts/src/fund.cairo
- contracts/tests/test_fund.cairo
- [ X] Added tests (if necessary)
- [ X] Run tests
1. Locate the set_name function in contracts/src/fund.cairo and enhance it by adding validation to ensure the caller is either VALID_ADDRESS_1 or VALID_ADDRESS_2.
2. Add a test to verify that the set_name function works correctly when called by VALID_ADDRESS_1 or VALID_ADDRESS_2.
3. Add a test to confirm that the set_name function does not work when called by an address other than VALID_ADDRESS_1 or VALID_ADDRESS_2.
2 hours.
Thank you for the opportunity to contribute to this great project
> [feat] Add asserts to set_name

- frontend/gostarkme-web/components/modules/Fund/Fund.tsx
- frontend/gostarkme-web/next.config.mjs
- Implemented owner check in the Fund component using `getOwner` from the contract.
- Added conditional rendering for "Withdraw" and "Donate" buttons based on ownership and fund state.
- Updated the `getDetails` function to include owner address retrieval.
- Enhanced error handling for fetching fund details.
- Improved user feedback with appropriate messages for different fund states.
Understanding Requirements and Planning(Repo structure): ~30 minutes
Implementing Owner Check and State Logic: ~1 hour
Conditional Rendering of Buttons: ~45 minutes
Refactoring getDetails Function: ~30 minutes
Super Happy to contribute to this amazing project, hope to keep contributing!!!
> feat: add owner check and conditional rendering for Fund component

- contracts/src/fund.cairo
- contracts/tests/test_fund.cairo
Locate the set_contact_handle function in contracts/src/fund.cairo and enhance it by adding validation to ensure the caller is either VALID_ADDRESS_1 or VALID_ADDRESS_2.
Add a test to verify that the set_contact_handle function works correctly when called by VALID_ADDRESS_1 and another for VALID_ADDRESS_2.
1 hour
Thank you for letting me contribute to the project.
> Feat: Assert-set-contact-handle

- contracts/src/fund.cairo
- contracts/tests/test_fund.cairo
-I remove assert where the fund manager can call the method set_method
-I add new assert that validate that the caller should be the admins in set_goal method in contracts/src/fund.cairo using the two  admins (VALID_ADDRESS_1,VALID_ADDRESS_2) constants located in contracts/src/constants/funds/fund_manager_constants.cairo
less than 24 hours, which is due to some installation issue on window
None, 
Thanks
> fix: Add new asserts to set_goal

- frontend/gostarkme-web/components/ui/Footer.tsx
> Fix footer links to redirect to blank page

- contracts/src/fund.cairo
- contracts/tests/test_fund.cairo
- [ x] Closes 259
- [ x] Added tests (if necessary)
- [x ] Run tests
- [x ] Commented the code
add a test for a set_contact_handle method, the test check with all authorized users and try with 1 another user, the test always fails because when another user try call the function the test fail
5 hours
i putted a #[should_panic] so if you remove this the test always fail
> Test: Set Contact Handle #259

- contracts/tests/test_fund.cairo
This PR adds a test for the set_goal method in contracts/src/fund.cairo. The new test validates that:
Only authorized addresses (VALID_ADDRESS_1 and VALID_ADDRESS_2) can call the set_goal method to set a new funding goal.
Unauthorized addresses are restricted from calling the method, ensuring the security and integrity of the fund goal-setting functionality.
- Before: There was no test validating the new assert logic in the set_goal method.
- After: The test suite now includes comprehensive coverage for the set_goal method, ensuring only admins can call it and that unauthorized access is properly restricted.
- Understanding the issue and analyzing requirements: 1 hour
- Writing and debugging the test cases: 1.5 hours
- Running and validating the tests: 1 hour (this is still on work, I …
> [test] add new set_goal test

- frontend/gostarkme-web/components/modules/Fund/FundVote.tsx
- frontend/gostarkme-web/components/modules/confirmation/Confirmation.tsx
Fix x confirmation message to be shorter
> Fix x confirmation message to be shorter

- src/fund.cairo
This pull request implements donor tracking functionality in the fund contract as requested in issue #327. The implementation introduces a permanent record of donor contributions while maintaining the contract's existing behavior.
Added legacy map for donor addresses and totals
- The LegacyMap creates an on-chain record that maps donor addresses to their total contributed amounts. When a new donor makes their first contribution, they are automatically initialized with a zero balance.
- Retrieves the caller's address once and stores it for consistent use
- Reads the donor's previous total from storage
- Updates their total by adding the new donation
- Maintains existing goal-checking logic
- Emits the donation event with proper donor attribution
- ✓ Added legacy map to store donator …
> [feat] #327 Add Legacy Map to Fund Contract for Donation Tracking

- src/fund.cairo
- The function get_single_donator_amount was defined in the contract trait
- The function returns the current value in  donators map according to the address entered or zero if not found.
- It was tested locally.
Around an hour. 
The test was no implemented due to there is another issue to test the function.
> #(331) Add Method to Retrieve a Single Donator

- src/fund_manager.cairo
• Introduce a LegacyMap to store the relationship between deployed fund contracts and their owners
• Update the new_fund method to register the caller address for each new fund
24 hours
Thanks for the opportunity
> Feat: Add fund_owner mapping and register owner in new_fund
