Makefile
src/fund.cairo
src/fundManager.cairo
src/lib.cairo

Closes #2 
TODO: deploy contracts from manager

[#2] added fundmanager

---

Makefile
Scarb.lock
Scarb.toml
src/fund.cairo
src/fundManager.cairo

[#6] deploying contracts from fund manager

---

README.md

Adding project info and contributiones to readme file

---

contracts/Makefile
contracts/src/fundManager.cairo

[feat] added mapping to funds by ID

---

contracts/Makefile
contracts/src/constants.cairo
contracts/src/constants/funds.cairo
contracts/src/constants/funds/state_constants.cairo
contracts/src/fund.cairo
contracts/src/fundManager.cairo
contracts/src/lib.cairo

[feat] added state logic for funds

---

frontend/gostarkme-web/app/page.tsx
frontend/gostarkme-web/components/welcomepage/WelcomeBar.tsx
frontend/gostarkme-web/components/welcomepage/WelcomeItems.tsx

[feat] added responsive css and min fixes

---

frontend/gostarkme-web/app/page.tsx
frontend/gostarkme-web/components/ui/LinkButton.tsx
frontend/gostarkme-web/components/welcomepage/WelcomeBar.tsx
frontend/gostarkme-web/package.json
frontend/gostarkme-web/yarn.lock

- Added responsive design
- Minor fixes

[feat] Frontend fixes

---

.github/workflows/nextjs.yml

[CI] add cache path

---

frontend/gostarkme-web/next.config.mjs

This will add the output config to nextjs config file

[CI] adding output config

---

frontend/gostarkme-web/next.config.mjs

This will fix basepath for deploying the github pages

[CI] fixing basePath

---

README.md
contracts/.snfoundry_cache/.prev_tests_failed
contracts/src/constants/funds.cairo
contracts/src/constants/funds/fund_constants.cairo
contracts/src/fund.cairo
contracts/tests/test_fund.cairo

Many todos in funds file, should be discuss @adrianvrj 
closes #13

Test funds

---

frontend/gostarkme-web/animations/StardustAnimation.tsx
frontend/gostarkme-web/app/page.tsx
frontend/gostarkme-web/components/welcomepage/WelcomeBar.tsx

This will add an stardust animation on the root page.

[feat] adding stardust animation on main page

---

.github/workflows/nextjs.yml

Fix NEXT_PUBLIC_APP_ROOT env var

[fix] updating NEXT_PUBLIC_APP_ROOT env var

---

frontend/gostarkme-web/.env.example
frontend/gostarkme-web/animations/StardustAnimation.tsx

This will add the absolute position to canvas in stardust animation

[fix] Stardust animation now absolute

---

.github/pull_request_template.md

[docs] added PR template

---

contracts/src/donatorManager.cairo

Add donator_class_hash in storage and send in constructor

---

frontend/gostarkme-web/app/myprofile/[useraddr]/page.tsx

Implemented the User Profile Page Feature
File: `frontend/gostarkme-web/app/myprofile/[useraddr]/page.tsx`
This PR introduces the `UserProfilePage` component, which displays a user's profile information, including their address, total donations, current level, and progress towards the next level following the figma design provided. The component leverages pre-existing UI components such as `ProgressBar` and `Divider` for consistency and reusability.
**User Address Display:** Shows a shortened version of the user's address for better readability.
**Total Donations:** Displays the total donations made by the user, accompanied by the Stark logo for branding.
**Current Level:** Indicates the user's current level within the application.
**Progress Bar:** Visually represents the user's progress …

[feat] Implement user profile page with progress bar and user details

---

contracts/README.md

Add Backend Setup Documentation

doc: add Backend Setup Documentation

---

frontend/gostarkme-web/app/app/fund/[fundId]/page.tsx
frontend/gostarkme-web/app/app/myprofile/[useraddr]/page.tsx
frontend/gostarkme-web/app/page.tsx
frontend/gostarkme-web/components/ui/Bounded.tsx
frontend/gostarkme-web/package.json

This PR will adjust some changes made during ODHack8 contributions

[fix] general ODHack contributions adjustments

---

.github/workflows/contract_checks.yml
contracts/src/fundManager.cairo

I made the CI more explicit by adding the following:
- Job to check for changes in the contracts directory, so that we don't repeat code in other jobs.
- Add if statements to multiple steps.
- Add explicit message indicating that no operation was performed since no changes were detected.
- Add `software-mansion` GitHub action to install `scarb`.
- CI of contracts is being run on PRs in the `dev` branch and on pushes in the `dev` and `main` branches.
Screenshot of the CI on my fork:
- Research: 1 day
- Implementation: 1 day
I'm open to any feedback or suggestions you may have for the CI :D

[CI] Fix CI Backend Pipeline

---

frontend/gostarkme-web/app/app/page.tsx
frontend/gostarkme-web/components/dashboard/fundCard.tsx
frontend/gostarkme-web/components/ui/Navbar.tsx
frontend/gostarkme-web/components/welcomepage/WelcomeBar.tsx

This PR will fix some small issues, will add navigation to users profile with dummy 1's direction and integrates the dashboard with the app

[feat] added navigation to user profile and integrate dashboard

---

.github/workflows/contract_checks.yml

Closes #115 
Changes snfoundry version in CI pipeline to test contracts properly

[CI] change snfoundry version

---

contracts/src/donator.cairo
contracts/src/donatorManager.cairo
contracts/tests/test_donator_manager.cairo

Add setup method in donator manager test to avoid repeat code
1 hour
This will avoid double code

Add setup method in donator manager test to avoid repeat code

---

contracts/tests/test_fund.cairo

Fix comments

---

contracts/src/donatorManager.cairo

- [#135] Closes #
This PR is adding the events section inside of the donatorManager contract
20 minutes

feat: Adding events to donatorManager contract

---

contracts/src/donatorManager.cairo
contracts/src/fundManager.cairo
contracts/tests/test_fund_manager.cairo

Fix variables and spaces

---

frontend/gostarkme-web/.env
frontend/gostarkme-web/app/app/myfunds/page.tsx
frontend/gostarkme-web/app/app/myprofile/page.tsx
frontend/gostarkme-web/components/modules/myfunds/UserFunds.tsx
frontend/gostarkme-web/components/ui/ConnectWalletButton.tsx
frontend/gostarkme-web/constants/index.ts
frontend/gostarkme-web/package.json
frontend/gostarkme-web/state/connectedWallet.ts

This PR will add the use of jotai's useAtom hook to store the wallet address.

[feat] use jotai to store wallet address

---

contracts/.snfoundry_cache/.prev_tests_failed
contracts/src/donatorManager.cairo
contracts/tests/test_donator_manager.cairo

Test event emit when deploying a donator contract
2 hours

Test event emit when deploying a donator contract

---

contracts/README.md
contracts/tests/test_fund.cairo

These tests verify that issue 183 #138 is correctly executed and make sure that the event emits the expected values, the tests pass successfully. In addition to some modifications in the readme.
I hope the solution solves what you requested, please let me know of any changes I need to make. Best regards.

[test] Test issued when the fund contract receives a donation

---

frontend/gostarkme-web/components/dashboard/fundCard.tsx
frontend/gostarkme-web/components/modules/Fund/FundVote.tsx
frontend/gostarkme-web/components/modules/myfunds/UserFunds.tsx
frontend/gostarkme-web/components/ui/ConnectWalletButton.tsx
frontend/gostarkme-web/components/ui/Divider.tsx
frontend/gostarkme-web/components/ui/Navbar.tsx

Deleting unused imports in frontend. 

Worked on deleting unused imports

---

frontend/gostarkme-web/app/app/fund/page.tsx
frontend/gostarkme-web/app/app/myfunds/page.tsx
frontend/gostarkme-web/app/app/myprofile/page.tsx
frontend/gostarkme-web/app/app/newfunding/page.tsx
frontend/gostarkme-web/app/app/page.tsx
frontend/gostarkme-web/components/modules/Fund/Fund.tsx
frontend/gostarkme-web/components/modules/Fund/FundVote.tsx
frontend/gostarkme-web/components/modules/myfunds/UserFunds.tsx
frontend/gostarkme-web/components/ui/ConnectWalletButton.tsx
frontend/gostarkme-web/components/ui/LoadingSpinner.tsx

This PR will add the following:
- Implementation of spinner when fetching data.
- Display new funding attributes in funding details page.
- General UI fixes

[feat] general fixes and added the new fields to funding detail page

---

frontend/gostarkme-web/app/app/myfunds/page.tsx
frontend/gostarkme-web/components/modules/Fund/Fund.tsx
frontend/gostarkme-web/components/modules/Fund/FundDonate.tsx
frontend/gostarkme-web/components/modules/newfunding/Stages.tsx
frontend/gostarkme-web/constants/index.ts
frontend/gostarkme-web/contracts/abis/strk.ts
frontend/gostarkme-web/contracts/addresses.ts
frontend/gostarkme-web/yarn.lock

This PR will add the donate functionality to the frontend for user to donate a fund

[feat] added donating functionality

---

frontend/README.md
frontend/gostarkme-web/app/app/confirmation/page.tsx
frontend/gostarkme-web/app/app/page.tsx
frontend/gostarkme-web/components/dashboard/fundCard.tsx
frontend/gostarkme-web/components/modules/Fund/Fund.tsx
frontend/gostarkme-web/components/modules/Fund/FundDonate.tsx
frontend/gostarkme-web/components/modules/Fund/FundVote.tsx
frontend/gostarkme-web/components/modules/confirmation/Confirmation.tsx
frontend/gostarkme-web/components/modules/confirmation/CreationConfirmation.tsx
frontend/gostarkme-web/components/modules/confirmation/DonationConfirmation.tsx
frontend/gostarkme-web/components/modules/confirmation/VoteConfirmation.tsx
frontend/gostarkme-web/components/modules/newfunding/Stages.tsx
frontend/gostarkme-web/components/ui/ShareOnX.tsx
frontend/gostarkme-web/package.json
frontend/gostarkme-web/state/latestTx.ts
frontend/gostarkme-web/state/nFunds.ts

This PR will add a confirmation page for whenever a user TX is executed.

[feat] Add confirmation page

---

contracts/src/fund.cairo
contracts/tests/test_fund.cairo
contracts/tests/test_fund_manager.cairo
frontend/gostarkme-web/components/modules/Fund/Fund.tsx
frontend/gostarkme-web/components/modules/Fund/FundDonate.tsx
frontend/gostarkme-web/components/modules/Fund/FundWithdraw.tsx
frontend/gostarkme-web/components/modules/newfunding/Stages.tsx
frontend/gostarkme-web/constants/index.ts
frontend/gostarkme-web/contracts/abis/fund.ts

Withdraw and deposit fix

---

frontend/gostarkme-web/app/app/page.tsx
frontend/gostarkme-web/components/dashboard/fundCard.tsx
frontend/gostarkme-web/constants/index.ts

This pr changes the fund manager that will be used for deploying the app.

[fix] modification in order to prepare launch

---

frontend/gostarkme-web/.gitignore
frontend/gostarkme-web/package-lock.json

The packa-lock needs to be added in order to deploy the app to prod

[fix] add package-lock to deploy prod

---

contracts/src/fund.cairo

fix set state in withdrawn method

---

contracts/src/donatorManager.cairo
contracts/tests/test_fund.cairo

Because this merge #193 some unit test broke

Fix unit test

---

contracts/src/fund.cairo
contracts/tests/test_fund.cairo

- add a test to ensure that admins cam change reason
- add a test to ensure that other user can't change reason
- distinguish reason_1 to reason_2 test datas
- format fund.cairo
```
❯ snforge test
Compiling gostarkme v0.1.0 (/home/nicolas/dev/contrib/web3/onlydust/od10/gostarkme/contracts/Scarb.toml)
Finished release target(s) in 5 seconds
Collected 35 test(s) from gostarkme package
Running 0 test(s) from src/
Running 35 test(s) from tests/
[PASS] tests::test_donator::test_get_owner (gas: ~296)
[PASS] tests::test_donator_manager::test_constructor (gas: ~527)
[PASS] tests::test_donator::test_get_level (gas: ~296)
[PASS] tests::test_donator::test_update_donator_values (gas: ~384)
[PASS] tests::test_fund::test_set_reason_unauthorized (gas: ~1653)
[PASS] …
```

Feat: add tests for the new set_reason behaviour implemented in #253

---

frontend/gostarkme-web/app/app/page.tsx

This PR removes the condition to show the dashboard only for connected users.
30min

feat: remove wallet conditions for the dashboard funds

---

contracts/Makefile
frontend/gostarkme-web/components/modules/Fund/Fund.tsx
frontend/gostarkme-web/components/modules/Fund/FundVote.tsx

[fix] general fixes to fund vote functionality

---

frontend/gostarkme-web/components/modules/Fund/FundDonate.tsx
frontend/gostarkme-web/components/modules/Fund/FundVote.tsx
frontend/gostarkme-web/components/ui/ConnectWalletButton.tsx
frontend/gostarkme-web/state/connectedWallet.ts

Feature to enable or disable vote, donate actions if the connected wallet is not on sepolia network.

feat: Check connection network

---

frontend/gostarkme-web/components/modules/Fund/Fund.tsx
frontend/gostarkme-web/components/modules/Fund/FundDonate.tsx

Fix tweet message to add amount

Fix is owner validation

---

frontend/gostarkme-web/constants/index.ts

Fetch fund manager from .env

---

frontend/gostarkme-web/components/modules/Fund/Fund.tsx

This PR will validate user connection when fetching details.

[fix] Validate user connection when fetching details

---

frontend/gostarkme-web/.env.example
frontend/gostarkme-web/app/app/page.tsx
frontend/gostarkme-web/components/modules/Fund/Fund.tsx
frontend/gostarkme-web/components/modules/Fund/FundWithdraw.tsx
frontend/gostarkme-web/constants/index.ts

This PR will allow us to manage the networks used for prod and dev

feat-308 managing rpc with .env var

---

frontend/gostarkme-web/.env.example
frontend/gostarkme-web/app/app/page.tsx
frontend/gostarkme-web/components/modules/Fund/Fund.tsx
frontend/gostarkme-web/components/modules/Fund/FundWithdraw.tsx
frontend/gostarkme-web/constants/index.ts

Mainnet deploy 1.0

---

.github/workflows/nextjs.yml

Mainnet deploy 1.0.1

---

src/fund.cairo

Removed validation logic in `fn withdraw`

[fix] Removed Validation from withdraw Method

---

src/fund.cairo

Implemented method to retrieve donators map.

#(329) implemented method to retrieve donators map

---

tests/test_fund.cairo

Added tests for test_get_single_donator_by_address method.
Tests:
• Verify the method correctly returns the total donation amount for a valid donator address.
• Test the behavior when the method is called with an address not present.
• Test the method with an address that has contributed multiple times to ensure the total amount is accurate.
• Validate the behavior when the map is empty and the method is called.

#332 Add get single donator tests

---

tests/test_fund.cairo

Remove unnecessary code on the test, this cause the expend of the gas.

#343 [bug] Fix fund unit test

---

src/fund.cairo

Fix while, while was wrong validation

#346 Fix get donators while

---

tests/test_fund.cairo

Added Tests for the donators Map retrieval function, to ascertain the mapstores all donators and their donations state.
6HRs
@all-contributors please add @@Abeeujah for code

test: Unit Tests for Donators Map Retrieval Method

---

src/fund_manager.cairo
tests/test_fund_manager.cairo

test: Fix unit test newFund method

---

src/fund_manager.cairo

Add new get_fund_owner method in fund manager

#358 Add new get_fund_owner method in fund manager

---

tests/test_fund_manager.cairo

- implement unit test for get all fund owners
- test cover for when fund array is empty and when array is not empty

[test]: unit test for get all funds array

---

.github/workflows/contract_checks.yml
Scarb.toml
test_local.sh
tests/test_fund_manager.cairo

Tests are ran in parallel using multiple threads to run a test suite, this is great, but could lead to rate limit problems when too many calls are made to the rpc endpoint during fork testing. 
My changes collects all the tests from the test suite and run the tests sequentially.

Fix CI Jobs and Local test script
